### ISSUE TITLE
нет смысла объявлять локальные переменные финальными

### ISSUE THREAD

**Issue by alfest** [lubaskinc0de/MyJavaLearning#2]
https://github.com/lubaskinc0de/MyJavaLearning/blob/9fa625022b7121dae5cdd438d7641881efd7dd94/Calculator.java#L28

нет смысла объявлять локальные переменные финальными

**Comment by lubaskinc0de** [comment]
почему?

**Comment by alfest** [comment]
это бывает нужно только в редких случаях, тебе это не надо.

**Comment by lubaskinc0de** [comment]
понял
