### ISSUE TITLE
float

### ISSUE THREAD

**Issue by alfest** [lubaskinc0de/MyJavaLearning#4]
https://github.com/lubaskinc0de/MyJavaLearning/blob/9fa625022b7121dae5cdd438d7641881efd7dd94/Calculator.java#L70

1. float практически никогда не используется, его точности не хватает даже для твоего калькулятора. Используй double.
2. Ты неправильно приводишь типы, ты преобразовываешь во float целочисленный результат целочисленных операций.

**Comment by lubaskinc0de** [comment]
1. исправлю, спасибо
2. на выходе пользователь всегда должен получать дабл

**Comment by alfest** [comment]
ну так ты неправильно приводишь тип, неважноо дабл или флоат.

**Comment by lubaskinc0de** [comment]
почему неправильно?

**Comment by alfest** [comment]
я же написал выше. 
твой неправильный вариант: (double) (3 / 2) = 1.0
правильный: (double) 3 / 2 = 1.5
