### ISSUE TITLE
Не надо склеивать ключи в строку

### ISSUE THREAD

**Issue by alfest** [lubaskinc0de/MyJavaLearning#5]
https://github.com/lubaskinc0de/MyJavaLearning/blob/9fa625022b7121dae5cdd438d7641881efd7dd94/Calculator.java#L50

Не нужно склеивать все ключи мапы в строку, чтобы потом в строке искать другую строку.
У мапы есть метод Map.containsKey(key)

**Comment by lubaskinc0de** [comment]
исправлю, спасибо
