### ISSUE TITLE
var

### ISSUE THREAD

**Issue by alfest** [lubaskinc0de/MyJavaLearning#7]
https://github.com/lubaskinc0de/MyJavaLearning/blob/9fa625022b7121dae5cdd438d7641881efd7dd94/Variables.java#L29

в джаве нет динамической типизации, компилятор статически определяет тип переменной по правой части выражения.

**Comment by lubaskinc0de** [comment]
наверное так, но все же это смахивает на динам. типизацию, а точное определение в комментарии вписывать бессмысленно, тк комментарии созданы для удобства чтения кода

**Comment by alfest** [comment]
Ты учишь джаву и думать, что var - это динамика - неправильно и вредно.

**Comment by lubaskinc0de** [comment]
окей
