### ISSUE TITLE
Просто для информации

### ISSUE THREAD

**Issue by alfest** [lubaskinc0de/MyJavaLearning#8]
https://github.com/lubaskinc0de/MyJavaLearning/blob/9fa625022b7121dae5cdd438d7641881efd7dd94/Calculator.java#L50-L64

Тебе наверное такое рано, но для информации, как такое часто делают в реальных проектах:

        double result = Optional.ofNullable(ACTIONS.get(action))
                .map(a -> a.apply(
                        getInput(scanner, "Введите первое число: ",
                                Scanner::nextInt),
                        getInput(scanner, "Введите второе число: ",
                                Scanner::nextInt)))
                .orElseThrow(() -> new IllegalArgumentException(
                        "Вы должны выбрать корректное действие"));

**Comment by lubaskinc0de** [comment]
что то страшное 😅
