### ISSUE TITLE
ответил тебе про приведение

### ISSUE THREAD

**Issue by alfest** [lubaskinc0de/MyJavaLearning#9]
я же написал выше. 
твой неправильный вариант: (double) (3 / 2) = 1.0
правильный: (double) 3 / 2 = 1.5

_Originally posted by @alfest in https://github.com/lubaskinc0de/MyJavaLearning/issues/4#issuecomment-1364517534_

**Comment by lubaskinc0de** [comment]
в первом случае мы приводим в дабл результат выражения, во втором цифру 3, в чем разница?

**Comment by lubaskinc0de** [comment]
хм, а 3/2 отдает нам флоат?

**Comment by lubaskinc0de** [comment]
а, там идет округление

**Comment by lubaskinc0de** [comment]
тогда если мы приводим в дабл 3 , то округления не происходит?

**Comment by lubaskinc0de** [comment]
т.к операция уже идет между даблом и числом?

**Comment by alfest** [comment]
при делении инта на инт получаем инт.  для того, чтобы получить дабл, нужно хотя бы одно из чисел привести к даблу.
